import json
import csv
import io
from typing import Any


def export_to_json(data: list[dict]) -> str:
    return json.dumps(data, indent=2, default=str)


def export_to_csv(data: list[dict]) -> str:
    if not data:
        return ""

    output = io.StringIO()
    if data:
        writer = csv.DictWriter(output, fieldnames=data[0].keys())
        writer.writeheader()
        writer.writerows(data)
    return output.getvalue()


def export_to_html(data: dict) -> str:
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Insight Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #f9fafb; color: #111827; }
        h1 { color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 30px; }
        .card { background: white; border-radius: 8px; padding: 20px; margin: 15px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .label { color: #6b7280; font-size: 0.875rem; }
        .value { color: #111827; font-weight: 500; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f3f4f6; }
        .footer { margin-top: 40px; font-size: 0.8rem; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <h1>Email Insight Report</h1>
"""

    def render_dict(d: dict, level: int = 0):
        nonlocal html
        if level == 0:
            html += '<div class="card">'
        for key, value in d.items():
            if isinstance(value, dict) and value:
                html += f'<h3 style="margin-top:20px">{key.replace("_", " ").title()}</h3>'
                html += '<div class="card">'
                render_dict(value, level + 1)
                html += '</div>'
            elif isinstance(value, list) and value:
                html += f'<h4>{key.replace("_", " ").title()}</h4>'
                html += '<table><tr><th>#</th><th>Value</th></tr>'
                for i, item in enumerate(value, 1):
                    if isinstance(item, dict):
                        html += f'<tr><td>{i}</td><td>'
                        for k, v in item.items():
                            html += f'<span class="label">{k}:</span> <span class="value">{v}</span><br>'
                        html += '</td></tr>'
                    else:
                        html += f'<tr><td>{i}</td><td>{item}</td></tr>'
                html += '</table>'
            else:
                label = key.replace("_", " ").title()
                html += f'<p><span class="label">{label}:</span> <span class="value">{value if value else "N/A"}</span></p>'
        if level == 0:
            html += '</div>'

    render_dict(data)

    html += """
    <div class="footer">
        <p>Generated by Email Insight &mdash; OSINT &amp; Business Intelligence Platform</p>
        <p>This report contains publicly available information only.</p>
    </div>
</body>
</html>"""
    return html
